name: Releases
on:
  push:
env:
  GOCRON2_VERSION: 1.6.6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/gocron2
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=all
          type=semver,pattern={{version}}-all
          type=semver,pattern={{major}}.{{minor}}-all
    - name: :all
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./all/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          GOCRON2_VERSION=${{env.GOCRON2_VERSION}}
    - id: meta_server
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/gocron2
        flavor: |
          latest=false
        tags: |
          type=raw,value=server
          type=semver,pattern={{version}}-server
          type=semver,pattern={{major}}.{{minor}}-server
    - name: :server
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./server/Dockerfile
        tags: ${{ steps.meta_server.outputs.tags }}
        build-args: |
          GOCRON2_VERSION=${{env.GOCRON2_VERSION}}
    - uses: actions/checkout@v4
    - uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        destination_container_repo: sstc/gocron2
        short_description: https://github.com/${{ github.repository }}
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
